### ISSUE TITLE
Directory Clean Up

### ISSUE THREAD

**Issue by RobotPsychologist** [Blood-Glucose-Control/bgl-meal-identification#4]
Can we get rid of the 0_meal_idenfication dir without breaking a bunch of code? Or is it easy to fix the code if it does break? Now that we do not have other projects in this repo it would make sense to organize the directory structure a little better so we can put a bow on this soon. 

Additionally, going through the files and deleting those that are not necessary. We should not have simulated data in this repo anymore, the data should be pulled directly from the benchmarking repo instead when doing runs on the simulated data.

**Comment by Tony911029** [comment]
@RobotPsychologist I will attempt to remove `0_meal_idenfication`. Might break some pipeline stuff but we will see

**Comment by Tony911029** [comment]
@RobotPsychologist Marked as done
